# Generated by Django 5.2.15 on 2026-08-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessMetricsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Выручка"
                    ),
                ),
                (
                    "cogs",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Себестоимость"
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Валовая прибыль"
                    ),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Расходы"
                    ),
                ),
                (
                    "salaries",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Зарплаты"
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Чистая прибыль"
                    ),
                ),
                (
                    "new_clients",
                    models.PositiveIntegerField(default=0, verbose_name="Новые клиенты"),
                ),
                ("new_leads", models.PositiveIntegerField(default=0, verbose_name="Новые лиды")),
                (
                    "qualified_leads",
                    models.PositiveIntegerField(default=0, verbose_name="Квалифицированные"),
                ),
                ("deals", models.PositiveIntegerField(default=0, verbose_name="Сделки")),
                (
                    "won_deals",
                    models.PositiveIntegerField(default=0, verbose_name="Выигранные сделки"),
                ),
                (
                    "lost_deals",
                    models.PositiveIntegerField(default=0, verbose_name="Проигранные сделки"),
                ),
                (
                    "won_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Выручка по сделкам",
                    ),
                ),
                (
                    "active_clients",
                    models.PositiveIntegerField(default=0, verbose_name="Активные клиенты"),
                ),
                (
                    "churned_clients",
                    models.PositiveIntegerField(default=0, verbose_name="Отток клиентов"),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True, verbose_name="Рассчитано")),
            ],
            options={
                "verbose_name": "Снапшот бизнес-метрик",
                "verbose_name_plural": "Снапшоты бизнес-метрик",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="SourceAcquisitionCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Сайт"),
                            ("referral", "Рекомендация"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("telegram", "Telegram"),
                            ("call", "Звонок"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Источник",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Год")),
                ("month", models.PositiveIntegerField(verbose_name="Месяц")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма затрат"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлен")),
            ],
            options={
                "verbose_name": "Стоимость привлечения",
                "verbose_name_plural": "Стоимости привлечения",
                "ordering": ["-year", "-month", "source"],
                "indexes": [
                    models.Index(
                        fields=["source", "year", "month"], name="analytics_s_source_d22e25_idx"
                    )
                ],
                "unique_together": {("source", "year", "month")},
            },
        ),
    ]
