# Generated by Django 5.2.15 on 2026-08-11 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0006_client_telegram_chat_id'),
        ('messaging', '0003_remove_conversation_uniq_contact_channel_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('channel', models.CharField(choices=[('all', 'Все каналы'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email')], default='all', max_length=20, verbose_name='Канал')),
                ('match_mode', models.CharField(choices=[('any', 'Любое из слов'), ('all', 'Все слова')], default='any', max_length=10, verbose_name='Условие совпадения')),
                ('keywords', models.JSONField(default=list, verbose_name='Ключевые слова')),
                ('reply_text', models.TextField(verbose_name='Ответ клиенту')),
                ('cooldown_minutes', models.PositiveIntegerField(default=0, verbose_name='Пауза между ответами (мин)')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет (меньше — раньше)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('trigger_count', models.PositiveIntegerField(default=0, verbose_name='Срабатываний')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее срабатывание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_keyword', models.CharField(blank=True, default='', max_length=255, verbose_name='Совпавшее слово')),
                ('status', models.CharField(choices=[('responded', 'Отправлен'), ('failed', 'Ошибка'), ('skipped', 'Пропущен')], default='responded', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_triggers', to='clients.client', verbose_name='Клиент')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_triggers', to='messaging.conversation', verbose_name='Диалог')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_triggers', to='messaging.message', verbose_name='Входящее сообщение')),
                ('reply_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_replies', to='messaging.message', verbose_name='Ответ')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='scenarios.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Срабатывание сценария',
                'verbose_name_plural': 'Срабатывания сценариев',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['is_active', 'channel'], name='scenarios_s_is_acti_455d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariotrigger',
            index=models.Index(fields=['scenario', 'created_at'], name='scenarios_s_scenari_bbfab5_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariotrigger',
            index=models.Index(fields=['conversation', 'created_at'], name='scenarios_s_convers_c5386a_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariotrigger',
            index=models.Index(fields=['created_at'], name='scenarios_s_created_71df4c_idx'),
        ),
    ]
