# Generated by Django 5.1.15 on 2026-09-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_client_telegram_chat_id"),
        ("messaging", "0003_remove_conversation_uniq_contact_channel_account_and_more"),
        ("scenarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="action_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Параметры действия, например {"days": 3} для неоплаченных счетов',
                verbose_name="Конфигурация действия",
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("reply", "Ответить клиенту"),
                    ("create_task", "Создать задачу"),
                    ("create_reminder", "Создать напоминание"),
                    ("create_project_demo", "Создать проект и демо-доступ"),
                ],
                default="reply",
                max_length=30,
                verbose_name="Действие",
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("message", "Входящее сообщение"),
                    ("lead_created", "Лид создан"),
                    ("deal_won", "Сделка выиграна"),
                    ("invoice_unpaid", "Счёт не оплачен"),
                    ("project_created", "Проект создан"),
                ],
                default="message",
                max_length=30,
                verbose_name="Событие",
            ),
        ),
        migrations.AddField(
            model_name="scenariotrigger",
            name="entity_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="ID сущности"),
        ),
        migrations.AddField(
            model_name="scenariotrigger",
            name="entity_label",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Сущность"),
        ),
        migrations.AddField(
            model_name="scenariotrigger",
            name="entity_type",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Тип сущности"
            ),
        ),
        migrations.AddField(
            model_name="scenariotrigger",
            name="event_type",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Событие"),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="reply_text",
            field=models.TextField(blank=True, default="", verbose_name="Ответ клиенту"),
        ),
        migrations.AlterField(
            model_name="scenariotrigger",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scenario_triggers",
                to="clients.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="scenariotrigger",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scenario_triggers",
                to="messaging.conversation",
                verbose_name="Диалог",
            ),
        ),
        migrations.AlterField(
            model_name="scenariotrigger",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scenario_triggers",
                to="messaging.message",
                verbose_name="Входящее сообщение",
            ),
        ),
    ]
