# Generated by Django 5.1.15 on 2026-09-19 15:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_expand_project_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cost_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Ставка за час (₽)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="hours_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Бюджет времени (часы)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tracked_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="Затрачено (часы)",
            ),
        ),
    ]
