# Generated by Django 5.1.15 on 2026-10-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_cost_per_hour_project_hours_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
