# Generated by Django 5.2.15 on 2026-08-08 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_phone_e164_alter_client_source'),
        ('finance', '0001_initial'),
        ('leads', '0002_lead_next_action_lead_next_action_at'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('client_no_response', 'Клиент не отвечает'), ('deal_stage_timeout', 'Сделка долго на этапе'), ('task_overdue', 'Просроченная задача'), ('task_deadline_soon', 'Близкий дедлайн задачи'), ('deal_no_next_action', 'Нет следующего действия по сделке'), ('lead_unprocessed', 'Лид не обработан'), ('client_no_contact', 'Клиент давно не контактировал'), ('deal_no_changes', 'Сделка без изменений'), ('client_open_deals_no_contact', 'Клиент с открытыми сделками без контакта'), ('finance_deadline_soon', 'Дедлайн счёта близко')], max_length=60, verbose_name='Тип правила')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Конфигурация правила, например {"days": 3}', verbose_name='Условия')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='Роли пользователей, которым создаются напоминания. Пусто — все роли.', verbose_name='Целевые роли')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Правило напоминания',
                'verbose_name_plural': 'Правила напоминаний',
                'ordering': ['type', 'name'],
                'indexes': [models.Index(fields=['type', 'enabled'], name='reminders_r_type_ea2791_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('viewed', 'Просмотрено'), ('completed', 'Выполнено'), ('dismissed', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='Статус')),
                ('due_at', models.DateTimeField(verbose_name='Когда')),
                ('snoozed_until', models.DateTimeField(blank=True, null=True, verbose_name='Отложено до')),
                ('dedup_key', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Ключ дедупликации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Отклонено в')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено в')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='clients.client', verbose_name='Клиент')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='leads.lead', verbose_name='Сделка')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='finance.invoice', verbose_name='Счёт')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='reminders.reminderrule', verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Создано'), ('viewed', 'Просмотрено'), ('completed', 'Выполнено'), ('dismissed', 'Отклонено'), ('snoozed', 'Отложено'), ('expired', 'Истекло'), ('system', 'Система')], max_length=20, verbose_name='Действие')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reminders.reminder', verbose_name='Напоминание')),
            ],
            options={
                'verbose_name': 'Журнал напоминания',
                'verbose_name_plural': 'Журналы напоминаний',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reminder', '-created_at'], name='reminders_r_reminde_fa5496_idx'), models.Index(fields=['actor', '-created_at'], name='reminders_r_actor_i_b9333d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'status', 'due_at'], name='reminders_r_user_id_777413_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', '-created_at'], name='reminders_r_user_id_3b819a_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['dedup_key'], name='reminders_r_dedup_k_c8953c_idx'),
        ),
    ]
