# Generated by Django 5.0.14 on 2026-08-08 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_assigned', models.BooleanField(default=True, verbose_name='Новые задачи')),
                ('comment_added', models.BooleanField(default=True, verbose_name='Комментарии')),
                ('project_updated', models.BooleanField(default=True, verbose_name='Изменения проектов')),
                ('deadline_reminder', models.BooleanField(default=True, verbose_name='Дедлайны')),
                ('message_received', models.BooleanField(default=True, verbose_name='Новые сообщения')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='Тихие часы')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Начало тихих часов')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Конец тихих часов')),
                ('digest_enabled', models.BooleanField(default=False, verbose_name='Дайджест')),
                ('digest_frequency', models.CharField(choices=[('never', 'Никогда'), ('daily', 'Раз в день'), ('weekly', 'Раз в неделю')], default='never', max_length=10, verbose_name='Частота дайджеста')),
                ('auto_archive_read_days', models.IntegerField(default=7, help_text='0 = не архивировать автоматически', verbose_name='Архивировать прочитанные через (дней)')),
                ('auto_archive_unread_days', models.IntegerField(default=30, help_text='0 = не архивировать автоматически', verbose_name='Архивировать непрочитанные через (дней)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('task_assigned', 'Назначена задача'), ('task_updated', 'Задача обновлена'), ('project_updated', 'Проект обновлён'), ('deadline_reminder', 'Напоминание о дедлайне'), ('message_received', 'Новое сообщение'), ('comment_added', 'Новый комментарий'), ('team_change', 'Изменение в команде'), ('system', 'Системное')], default='system', max_length=50, verbose_name='Тип')),
                ('urgency', models.CharField(choices=[('critical', '🔴 Критично'), ('important', '🟡 Важно'), ('info', '🔵 Информация')], default='info', max_length=20, verbose_name='Срочность')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('related_project_id', models.UUIDField(blank=True, null=True, verbose_name='ID проекта')),
                ('related_task_id', models.UUIDField(blank=True, null=True, verbose_name='ID задачи')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'read'], name='notificatio_user_id_878a13_idx'), models.Index(fields=['user', 'archived'], name='notificatio_user_id_8d1f60_idx')],
            },
        ),
    ]
