# Generated by Django 5.0.14 on 2026-08-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Назначена задача'), ('task_updated', 'Задача обновлена'), ('project_updated', 'Проект обновлён'), ('deadline_reminder', 'Напоминание о дедлайне'), ('message_received', 'Новое сообщение'), ('missed_call', 'Пропущенный звонок'), ('comment_added', 'Новый комментарий'), ('team_change', 'Изменение в команде'), ('system', 'Системное')], default='system', max_length=50, verbose_name='Тип'),
        ),
    ]
