# Generated by Django 5.0.14 on 2026-06-24 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('prompt_type', models.CharField(choices=[('tz', 'Техническое задание'), ('commercial_offer', 'Коммерческое предложение'), ('contract', 'Договор'), ('report', 'Отчет'), ('summary', 'Суммаризация'), ('estimate', 'Оценка стоимости'), ('client_response', 'Ответ клиенту')], max_length=50, verbose_name='Тип промпта')),
                ('system_prompt', models.TextField(verbose_name='Системный промпт')),
                ('user_prompt_template', models.TextField(verbose_name='Шаблон промпта пользователя')),
                ('variables_schema', models.JSONField(blank=True, default=dict, verbose_name='Схема переменных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Шаблон промпта',
                'verbose_name_plural': 'Шаблоны промптов',
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_type', models.CharField(max_length=50, verbose_name='Тип запроса')),
                ('input_data', models.JSONField(default=dict, verbose_name='Входные данные')),
                ('output_data', models.TextField(blank=True, verbose_name='Результат')),
                ('model', models.CharField(default='gpt-4', max_length=100, verbose_name='Модель')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Токенов использовано')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_assistant.aiprompttemplate', verbose_name='Шаблон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'AI запрос',
                'verbose_name_plural': 'AI запросы',
                'ordering': ['-created_at'],
            },
        ),
    ]
