# Generated by Django 5.2.15 on 2026-08-08 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('clients', '0001_initial'),
        ('finance', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название кампании')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('running', 'Запущен'), ('completed', 'Завершен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_tests', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_tests', to='leads.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'A/B тест кампания',
                'verbose_name_plural': 'A/B тест кампании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название варианта')),
                ('focus', models.CharField(choices=[('price', 'Акцент на цену'), ('timeline', 'Акцент на сроки'), ('quality', 'Акцент на качество'), ('features', 'Акцент на функционал'), ('support', 'Акцент на поддержку'), ('roi', 'Акцент на окупаемость'), ('cases', 'Акцент на кейсы')], default='price', max_length=50, verbose_name='Акцент')),
                ('content', models.TextField(verbose_name='Содержание КП')),
                ('style_tags', models.JSONField(blank=True, default=list, verbose_name='Теги стиля')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Отправлено')),
                ('viewed_count', models.IntegerField(default=0, verbose_name='Просмотрено')),
                ('converted_count', models.IntegerField(default=0, verbose_name='Конверсий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('ai_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_assistant.airequest', verbose_name='AI запрос')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ai_assistant.abtestcampaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Вариант КП',
                'verbose_name_plural': 'Варианты КП',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABTestConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлено клиенту')),
                ('converted', models.BooleanField(default=False, verbose_name='Конвертировано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Конвертировано')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_conversions', to='finance.invoice', verbose_name='Счет')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_conversions', to='leads.lead', verbose_name='Лид')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='ai_assistant.campaignvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Конверсия A/B теста',
                'verbose_name_plural': 'Конверсии A/B тестов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='abtestcampaign',
            name='winner_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_campaigns', to='ai_assistant.campaignvariant', verbose_name='Вариант-победитель'),
        ),
    ]
