# Generated by Django 5.2.15 on 2026-08-08 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_abtestcampaign_campaignvariant_abtestconversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(blank=True, default='', max_length=500, verbose_name='API URL')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='API ключ')),
                ('model', models.CharField(blank=True, default='', max_length=200, verbose_name='Модель')),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=3, verbose_name='Температура')),
                ('max_tokens', models.IntegerField(default=2048, verbose_name='Макс. токенов')),
                ('timeout', models.IntegerField(default=60, verbose_name='Таймаут (сек)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Настройки AI',
                'verbose_name_plural': 'Настройки AI',
            },
        ),
    ]
