# Generated by Django 5.0.14 on 2026-08-08 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('team_type', models.CharField(choices=[('department', 'Отдел'), ('team', 'Команда'), ('group', 'Группа')], default='team', max_length=20, verbose_name='Тип')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_teams', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='structure.team', verbose_name='Вышестоящее подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('head', 'Руководитель'), ('deputy', 'Заместитель'), ('member', 'Участник'), ('trainee', 'Стажёр')], default='member', max_length=20, verbose_name='Роль в команде')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('joined_at', models.DateField(blank=True, null=True, verbose_name='Дата вступления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='structure.team', verbose_name='Подразделение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
                'ordering': ['team', 'role', 'user__first_name'],
                'unique_together': {('team', 'user')},
            },
        ),
    ]
