# Generated by Django 5.1.15 on 2026-08-08 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_phone_e164_alter_client_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('business_account_id', models.CharField(max_length=64, verbose_name='Business Account ID (WABA)')),
                ('phone_number_id', models.CharField(max_length=64, verbose_name='Phone Number ID')),
                ('display_phone_number', models.CharField(max_length=32, verbose_name='Номер телефона')),
                ('access_token_encrypted', models.TextField(blank=True, default='', verbose_name='Access token (зашифрован)')),
                ('webhook_verify_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Webhook verify token')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('disabled', 'Отключён'), ('invalid_credentials', 'Неверные учётные данные'), ('rate_limited', 'Превышен лимит запросов')], default='active', max_length=32, verbose_name='Статус')),
                ('is_default', models.BooleanField(default=False, verbose_name='Использовать по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'WhatsApp аккаунт',
                'verbose_name_plural': 'WhatsApp аккаунты',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email')], default='whatsapp', max_length=20, verbose_name='Канал')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('pending', 'Ожидание'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус')),
                ('last_customer_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение клиента')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение')),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=255, verbose_name='Превью последнего')),
                ('unread_count', models.IntegerField(default=0, verbose_name='Непрочитанные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_conversations', to='clients.client', verbose_name='Клиент')),
                ('whatsapp_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='messaging.whatsappaccount', verbose_name='WhatsApp аккаунт')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email')], default='whatsapp', max_length=20, verbose_name='Канал')),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=10, verbose_name='Направление')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('document', 'Документ'), ('audio', 'Аудио'), ('video', 'Видео'), ('template', 'Шаблон'), ('location', 'Геолокация'), ('sticker', 'Стикер'), ('contact', 'Контакт'), ('system', 'Системное')], default='text', max_length=20, verbose_name='Тип')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('media_url', models.URLField(blank=True, max_length=2048, verbose_name='URL медиа')),
                ('media_name', models.CharField(blank=True, max_length=255, verbose_name='Имя медиа')),
                ('media_mime', models.CharField(blank=True, max_length=100, verbose_name='MIME')),
                ('external_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='ID сообщения (провайдер)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('read', 'Прочитано'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Код ошибки')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_messages', to='clients.client', verbose_name='Клиент')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation', verbose_name='Диалог')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messaging_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель (сотрудник)')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='messaging_m_convers_7bc91b_idx'), models.Index(fields=['contact', 'created_at'], name='messaging_m_contact_e5594d_idx'), models.Index(fields=['channel'], name='messaging_m_channel_d8e702_idx'), models.Index(fields=['status'], name='messaging_m_status_7d189b_idx'), models.Index(fields=['created_at'], name='messaging_m_created_d51bc4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_message_id', ''), _negated=True), fields=('external_message_id',), name='uniq_external_message_id')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['contact', 'channel'], name='messaging_c_contact_432e49_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_user', 'status'], name='messaging_c_assigne_90a644_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['channel', 'status'], name='messaging_c_channel_9f9faa_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='messaging_c_last_me_3f31f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('whatsapp_account__isnull', False)), fields=('contact', 'channel', 'whatsapp_account'), name='uniq_contact_channel_account'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('whatsapp_account__isnull', True)), fields=('contact', 'channel'), name='uniq_contact_channel_no_account'),
        ),
    ]
