# Generated by Django 5.0.14 on 2026-08-11 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('bot_token_encrypted', models.TextField(blank=True, default='', verbose_name='Bot token (зашифрован)')),
                ('bot_username', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Username бота')),
                ('bot_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя бота')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=64, verbose_name='Webhook secret token')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('disabled', 'Отключён'), ('invalid_credentials', 'Неверные учётные данные'), ('rate_limited', 'Превышен лимит запросов')], default='active', max_length=32, verbose_name='Статус')),
                ('is_default', models.BooleanField(default=False, verbose_name='Использовать по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Telegram бот',
                'verbose_name_plural': 'Telegram боты',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
