# Generated by Django 5.0.14 on 2026-08-11 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_telegram_chat_id'),
        ('messaging', '0002_telegramaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='uniq_contact_channel_account',
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='uniq_contact_channel_no_account',
        ),
        migrations.AddField(
            model_name='conversation',
            name='telegram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='messaging.telegramaccount', verbose_name='Telegram бот'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram chat_id'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_account__isnull', True), ('whatsapp_account__isnull', False)), fields=('contact', 'channel', 'whatsapp_account'), name='uniq_contact_channel_account'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_account__isnull', False), ('whatsapp_account__isnull', True)), fields=('contact', 'channel', 'telegram_account'), name='uniq_contact_channel_telegram_account'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_account__isnull', True), ('whatsapp_account__isnull', True)), fields=('contact', 'channel'), name='uniq_contact_channel_no_account'),
        ),
    ]
