# Generated by Django 5.1.15 on 2026-10-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('messaging', '0003_remove_conversation_uniq_contact_channel_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='deals.deal'),
        ),
    ]
