# Generated by Django 5.2.15 on 2026-08-08 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает согласования'), ('approved', 'Согласован'), ('rejected', 'Отклонен'), ('in_progress', 'В работе')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Согласовано')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('deliverable_url', models.URLField(blank=True, verbose_name='URL результата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_milestones', to=settings.AUTH_USER_MODEL, verbose_name='Согласовал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Этап проекта',
                'verbose_name_plural': 'Этапы проекта',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('general', 'Общий отзыв'), ('approval', 'Согласование'), ('revision', 'Правки')], default='general', max_length=20, verbose_name='Тип отзыва')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка (1-5)')),
                ('attachment_url', models.URLField(blank=True, verbose_name='URL вложения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='clients.client', verbose_name='Клиент')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='projects.project', verbose_name='Проект')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='cabinet.projectmilestone', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='Токен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Ссылка для шаринга',
                'verbose_name_plural': 'Ссылки для шаринга',
            },
        ),
    ]
