const crmLabels = <String, String>{
  'ids': 'Позиции каталога',
  'percent': 'Изменение цены, %',
  'action': 'Действие',
  'campaign_name': 'Название кампании',
  'campaign_id': 'Кампания',
  'focuses': 'Акценты (выберите от 2 до 5)',
  'invoice_id': 'Счёт',
  'tasks_assigned': 'Назначенные задачи',
  'tasks_completed': 'Завершённые задачи',
  'tasks_due': 'Задачи со сроком',
  'hours_tracked': 'Затраченное время',
  'task_assigned': 'Назначение задач',
  'comment_added': 'Новые комментарии',
  'project_updated': 'Изменения проектов',
  'deadline_reminder': 'Напоминания о сроках',
  'message_received': 'Новые сообщения',
  'quiet_hours_enabled': 'Тихие часы',
  'digest_enabled': 'Сводка уведомлений',
  'period': 'Отложить на',
  'recovery_codes': 'Резервные коды',
  'matched': 'Совпадение',
  'keyword': 'Ключевое слово',
  'contact_id': 'Клиент',
  'whatsapp_account_id': 'Аккаунт WhatsApp',
  'telegram_account_id': 'Аккаунт Telegram',
  'days': 'Через сколько дней',
  'project_role': 'Роль в проекте',
  'create_milestone': 'Создать этап проекта',
  'milestone_name': 'Название этапа',
  'name': 'Название',
  'title': 'Название',
  'description': 'Описание',
  'content': 'Текст',
  'text': 'Сообщение',
  'first_name': 'Имя',
  'last_name': 'Фамилия',
  'full_name': 'Имя',
  'contact_name': 'Контактное лицо',
  'company_name': 'Компания',
  'phone': 'Телефон',
  'email': 'Email',
  'telegram': 'Telegram',
  'client': 'Клиент',
  'client_name': 'Клиент',
  'project': 'Проект',
  'project_name': 'Проект',
  'status': 'Статус',
  'status_name': 'Статус',
  'status_id': 'Статус',
  'stage_id': 'Этап',
  'current_stage': 'Этап',
  'stage_name': 'Этап',
  'status_color': 'Цвет статуса',
  'stage_color': 'Цвет этапа',
  'assignee': 'Исполнитель',
  'assignee_name': 'Исполнитель',
  'assigned_to': 'Ответственный',
  'assigned_to_name': 'Ответственный',
  'reviewer': 'Проверяющий',
  'created_by_name': 'Автор',
  'budget': 'Бюджет',
  'cost': 'Стоимость',
  'deadline': 'Срок',
  'progress': 'Прогресс',
  'service_type': 'Услуга',
  'hours_budget': 'Плановые часы',
  'cost_per_hour': 'Стоимость часа',
  'priority': 'Приоритет',
  'priority_name': 'Приоритет',
  'estimated_hours': 'Плановые часы',
  'actual_hours': 'Затраченные часы',
  'parent_task': 'Родительская задача',
  'notes': 'Заметки',
  'next_action': 'Следующее действие',
  'next_action_at': 'Дата следующего действия',
  'source': 'Источник',
  'is_active': 'Активно',
  'created_at': 'Создано',
  'updated_at': 'Обновлено',
  'number': 'Номер',
  'amount': 'Сумма',
  'paid_amount': 'Оплачено',
  'issued_date': 'Дата выставления',
  'due_date': 'Срок оплаты',
  'paid_at': 'Дата оплаты',
  'invoice': 'Счёт',
  'method': 'Способ оплаты',
  'transaction_id': 'Номер транзакции',
  'category': 'Категория',
  'category_name': 'Категория',
  'expense_date': 'Дата расхода',
  'income_date': 'Дата дохода',
  'month': 'Месяц',
  'year': 'Год',
  'user': 'Сотрудник',
  'user_id': 'Сотрудник',
  'user_name': 'Сотрудник',
  'role': 'Роль',
  'role_name': 'Роль',
  'role_in_project': 'Роль в проекте',
  'document_type': 'Тип документа',
  'document_type_name': 'Тип документа',
  'file': 'Файл',
  'file_name': 'Название файла',
  'external_url': 'Внешняя ссылка',
  'preview_url': 'Просмотр',
  'approval_assignee': 'Согласующий',
  'approval_deadline': 'Срок согласования',
  'is_visible_to_client': 'Виден клиенту',
  'is_protected': 'Защищён',
  'allowed_roles': 'Доступные роли',
  'document': 'Документ',
  'document_id': 'Документ',
  'type': 'Тип',
  'sku': 'Артикул',
  'price': 'Цена',
  'cost_price': 'Себестоимость',
  'stock': 'Остаток',
  'unit': 'Единица измерения',
  'quantity': 'Количество',
  'discount': 'Скидка',
  'tax': 'Налог',
  'item': 'Товар или услуга',
  'items': 'Позиции',
  'package_items': 'Состав пакета',
  'unit_price': 'Цена за единицу',
  'low_stock_threshold': 'Минимальный остаток',
  'duration_minutes': 'Длительность, минуты',
  'billing_period': 'Период оплаты',
  'next_billing_date': 'Следующая оплата',
  'image': 'Изображение',
  'reason': 'Причина',
  'note': 'Заметка',
  'lead': 'Лид',
  'lead_id': 'Лид',
  'total': 'Итого',
  'profit': 'Прибыль',
  'margin': 'Маржа',
  'remaining': 'Остаток к оплате',
  'channel': 'Канал',
  'event_type': 'Событие',
  'action_type': 'Действие',
  'match_mode': 'Условие совпадения',
  'keywords': 'Ключевые слова',
  'reply_text': 'Текст ответа',
  'cooldown_minutes': 'Пауза, минуты',
  'action_config': 'Настройки действия',
  'priority_order': 'Порядок',
  'order': 'Порядок',
  'color': 'Цвет',
  'probability': 'Вероятность',
  'mentor': 'Наставник',
  'mentee': 'Стажёр',
  'team': 'Команда',
  'start_date': 'Дата начала',
  'end_date': 'Дата завершения',
  'slug': 'Адрес статьи',
  'category_display': 'Категория',
  'is_published': 'Опубликовано',
  'entity_type': 'Тип записи',
  'form_fields': 'Поля формы',
  'create_lead': 'Создавать лид',
  'link_lifetime': 'Срок ссылки',
  'public_url': 'Публичная ссылка',
  'lead_field_map': 'Связь полей с лидом',
  'key': 'Ключ',
  'label': 'Подпись',
  'required': 'Обязательно',
  'options': 'Варианты',
  'placeholder': 'Подсказка',
  'template': 'Шаблон',
  'recipient_email': 'Email получателя',
  'expires_at': 'Действует до',
  'due_at': 'Срок',
  'completed': 'Завершено',
  'old_password': 'Текущий пароль',
  'new_password': 'Новый пароль',
  'password': 'Пароль',
  'code': 'Код подтверждения',
  'api_key': 'Ключ API',
  'base_url': 'Адрес провайдера',
  'model': 'Модель',
  'temperature': 'Температура',
  'system_prompt': 'Системная инструкция',
  'prompt': 'Запрос',
  'variables': 'Данные для генерации',
  'is_group': 'Групповой чат',
  'participant_ids': 'Участники',
  'user_ids': 'Участники',
  'sender_name': 'Отправитель',
  'message_type': 'Тип сообщения',
  'direction': 'Направление',
  'phone_number_id': 'ID номера WhatsApp',
  'business_account_id': 'ID аккаунта WhatsApp',
  'access_token': 'Токен доступа',
  'bot_token': 'Токен бота',
  'webhook_secret': 'Секрет webhook',
  'webhook_url': 'Адрес webhook',
};
String crmLabel(String key, [String? fallback]) =>
    crmLabels[key] ?? fallback ?? key.replaceAll('_', ' ');

const crmLookups = <String, String>{
  'client_id': '/clients/',
  'invoice_id': '/finance/invoices/',
  'contact_id': '/clients/',
  'whatsapp_account_id': '/messaging/whatsapp/accounts/',
  'telegram_account_id': '/messaging/telegram/accounts/',
  'client': '/clients/',
  'project': '/projects/',
  'service_type': '/projects/service-types/',
  'assignee': '/auth/users/',
  'assigned_to': '/auth/users/',
  'reviewer': '/auth/users/',
  'user': '/auth/users/',
  'user_id': '/auth/users/',
  'mentor': '/auth/users/',
  'mentee': '/auth/users/',
  'approval_assignee': '/auth/users/',
  'participant_ids': '/auth/users/',
  'user_ids': '/auth/users/',
  'parent_task': '/tasks/',
  'invoice': '/finance/invoices/',
  'document_type': '/documents/types/',
  'document': '/documents/',
  'document_id': '/documents/',
  'deal': '/deals/',
  'lead': '/leads/',
  'lead_id': '/leads/',
  'item': '/catalog/items/',
  'team': '/structure/teams/',
  'template': '/forms/',
};
