# Generated by Django 5.2.15 on 2026-08-08 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_phone_e164_alter_client_source_and_more'),
        ('finance', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'paid_at'], name='finance_inv_status_d5a99b_idx'),
        ),
    ]
