# Generated by Django 5.1.15 on 2026-10-04 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_income'),
        ('projects', '0005_project_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position', models.PositiveSmallIntegerField()),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_milestone', to='finance.invoice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_milestones', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'position'],
                'constraints': [models.UniqueConstraint(fields=('project', 'position'), name='unique_project_payment_position')],
            },
        ),
    ]
