# Generated by Django 5.2.15 on 2026-08-08 12:39

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("color", models.CharField(default="#6366f1", max_length=7, verbose_name="Цвет")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
            ],
            options={
                "verbose_name": "Категория каталога",
                "verbose_name_plural": "Категории каталога",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product", "Товар"),
                            ("service", "Услуга"),
                            ("package", "Пакет"),
                            ("subscription", "Подписка"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True, verbose_name="Артикул"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Себестоимость",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Налог (%)",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Скидка (%)",
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="Остаток")),
                (
                    "low_stock_threshold",
                    models.IntegerField(default=5, verbose_name="Порог низкого остатка"),
                ),
                ("unit", models.CharField(default="шт.", max_length=50, verbose_name="Ед. изм.")),
                (
                    "duration_minutes",
                    models.IntegerField(blank=True, null=True, verbose_name="Длительность (мин)"),
                ),
                (
                    "billing_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Ежемесячно"),
                            ("quarterly", "Ежеквартально"),
                            ("yearly", "Ежегодно"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Период оплаты",
                    ),
                ),
                (
                    "next_billing_date",
                    models.DateField(blank=True, null=True, verbose_name="Следующая оплата"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="catalog/%Y/%m/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("inactive", "Неактивен"),
                            ("archived", "В архиве"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлен")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="catalog.catalogcategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция каталога",
                "verbose_name_plural": "Позиции каталога",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("sale", "Продажа"),
                            ("restock", "Приход"),
                            ("adjustment", "Корректировка"),
                            ("refund", "Возврат"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество (+/-)")),
                ("balance_after", models.IntegerField(verbose_name="Остаток после")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ссылка (сделка и т.п.)"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_movements",
                        to="catalog.catalogitem",
                        verbose_name="Позиция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение остатков",
                "verbose_name_plural": "Движения остатков",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="Количество"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="included_in_packages",
                        to="catalog.catalogitem",
                        verbose_name="Позиция",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_items",
                        to="catalog.catalogitem",
                        verbose_name="Пакет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция пакета",
                "verbose_name_plural": "Позиции пакетов",
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Старая цена",
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Новая цена"),
                ),
                (
                    "old_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Старая себестоимость",
                    ),
                ),
                (
                    "new_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Новая себестоимость",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, verbose_name="Причина")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изменил",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="catalog.catalogitem",
                        verbose_name="Позиция",
                    ),
                ),
            ],
            options={
                "verbose_name": "История цены",
                "verbose_name_plural": "Истории цен",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(fields=["type", "status"], name="catalog_cat_type_3a901f_idx"),
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(fields=["category", "type"], name="catalog_cat_categor_f46212_idx"),
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(fields=["sku"], name="catalog_cat_sku_6b916d_idx"),
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(
                fields=["status", "created_at"], name="catalog_cat_status_2939c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["item", "created_at"], name="catalog_inv_item_id_88fe7b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="packageitem",
            unique_together={("package", "item")},
        ),
    ]
