# Generated by Django 5.1.15 on 2026-09-19 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("client", "Анкета клиента"),
                            ("employee", "Анкета сотрудника"),
                            ("other", "Другое"),
                        ],
                        default="client",
                        max_length=20,
                        verbose_name="Тип анкеты",
                    ),
                ),
                (
                    "form_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Список полей: {"key","label","type","required","options"}',
                        verbose_name="Поля",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлена")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_form_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон анкеты",
                "verbose_name_plural": "Шаблоны анкет",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="Токен"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Имя получателя"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email получателя"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("client", "Анкета клиента"),
                            ("employee", "Анкета сотрудника"),
                            ("other", "Другое"),
                        ],
                        default="client",
                        max_length=20,
                        verbose_name="Тип анкеты",
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID сущности (клиент/сотрудник)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Отправлена"),
                            ("filled", "Заполнена"),
                            ("expired", "Истекла"),
                        ],
                        default="sent",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ссылка действует до"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Заполнена"),
                ),
                ("response", models.JSONField(blank=True, default=dict, verbose_name="Ответ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_form_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="forms.formtemplate",
                        verbose_name="Анкета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка анкеты",
                "verbose_name_plural": "Ссылки анкет",
                "ordering": ["-created_at"],
            },
        ),
    ]
