# Generated by Django 6.0.8 on 2026-09-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_public_form_links"),
        ("leads", "0003_lead_leads_lead_created_302c6d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="forminvitation",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_invitations",
                to="leads.lead",
                verbose_name="Созданный лид",
            ),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="create_lead",
            field=models.BooleanField(default=False, verbose_name="Создавать лид из заявки"),
        ),
        migrations.AddField(
            model_name="formtemplate",
            name="lead_field_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Словарь: {"атрибут_лида": "ключ_поля_анкеты"}',
                verbose_name="Маппинг полей лида",
            ),
        ),
    ]
