# Generated by Django 5.2.15 on 2026-08-08 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='employees/photos/', verbose_name='Фотография')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Навыки')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Социальные сети')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, verbose_name='Контакт для экстренной связи')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('issuer', models.CharField(blank=True, max_length=255, verbose_name='Организация')),
                ('file', models.FileField(upload_to='employees/certificates/', verbose_name='Файл')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('expires_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.employeeprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issued_date', '-created_at'],
            },
        ),
    ]
