# Generated by Django 5.0.14 on 2026-10-03 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_seed_task_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FocusProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_minutes', models.PositiveSmallIntegerField(default=25)),
                ('short_break_minutes', models.PositiveSmallIntegerField(default=5)),
                ('long_break_minutes', models.PositiveSmallIntegerField(default=15)),
                ('cycles', models.PositiveSmallIntegerField(default=4)),
                ('daily_goal', models.PositiveSmallIntegerField(default=4)),
                ('theme', models.CharField(default='midnight', max_length=20)),
                ('timer_style', models.CharField(default='digital', max_length=20)),
                ('auto_advance', models.BooleanField(default=False)),
                ('sound', models.CharField(default='none', max_length=20)),
                ('pet', models.CharField(default='bee', max_length=20)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('inventory', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='focus_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('work', 'Работа'), ('short_break', 'Короткий перерыв'), ('long_break', 'Длинный перерыв')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Идёт'), ('paused', 'На паузе'), ('completed', 'Завершена'), ('cancelled', 'Остановлена')], default='running', max_length=20)),
                ('goal', models.CharField(blank=True, max_length=300)),
                ('result', models.TextField(blank=True)),
                ('planned_seconds', models.PositiveIntegerField()),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='tasks.task')),
                ('timer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tasktimer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='tasks_focus_user_id_257760_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='focussession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['running', 'paused'])), fields=('user',), name='one_active_focus_per_user'),
        ),
    ]
