"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/shared/api/base";
type Project = { id: string; name: string; budget: string | null };
type Milestone = { id: number; project_name: string; title: string; percentage: string; amount: string; paid_amount: string; remaining: string; due_date: string; status: "planned" | "partial" | "overdue" | "paid" };
type Forecast = { currency: string; as_of: string; overdue: string; unforecasted_deals: number; windows: Record<string,{end_date:string;scheduled_invoices:string;weighted_open_deals:string;expected:string;deals_count:number}> };
const today=(n:number)=>{ const d=new Date(); d.setDate(d.getDate()+n); return d.toISOString().slice(0,10); };
export function PaymentPlanning() {
 const cache=useQueryClient(); const [project,setProject]=useState(""); const [error,setError]=useState("");
 const projects=useQuery({queryKey:["projects","payment-plan"],queryFn:async()=> (await api.get<{results:Project[]}>("/projects/",{params:{page_size:100}})).data.results});
 const plan=useQuery({queryKey:["payment-plan",project],queryFn:async()=> (await api.get<{results:Milestone[]}>("/finance/payment-plan/",{params:{project,page_size:100}})).data.results});
 const forecast=useQuery({queryKey:["cash-flow-forecast"],queryFn:async()=> (await api.get<Forecast>("/finance/forecast/")).data});
 const create=useMutation({mutationFn:(data:object)=>api.post("/finance/payment-plan/",data),onSuccess:()=>{setError("");cache.invalidateQueries({queryKey:["payment-plan"]});cache.invalidateQueries({queryKey:["cash-flow-forecast"]});cache.invalidateQueries({queryKey:["financial-control"]});},onError:()=>setError("Проверьте бюджет и распределение процентов. Для проекта можно создать только один график.")});
 const money=(s:string,c=forecast.data?.currency||"KGS")=>`${Number(s).toLocaleString("ru-RU",{maximumFractionDigits:2})} ${c}`;
 const titles=["Предоплата","После дизайна","После разработки","После запуска"];
 return <div className="space-y-6">
  <section className="card space-y-4"><h2 className="text-lg font-semibold">Прогноз поступлений · {forecast.data?.currency||"KGS"}</h2>{forecast.isError&&<p role="alert">Прогноз доступен владельцу. Повторите загрузку.</p>}{forecast.isLoading&&<p>Загрузка…</p>}{forecast.data&&<><p className="text-sm text-surface-500">На {forecast.data.as_of}. Учитываем остатки выставленных счетов и сделки с датой завершения, взвешенные по вероятности этапа. Это план, не гарантия поступления.</p><p>Просрочено к оплате: <strong>{money(forecast.data.overdue)}</strong></p><div className="grid gap-4 sm:grid-cols-3">{Object.entries(forecast.data.windows).map(([days,w])=><article className="rounded-xl border border-surface-200 p-4" key={days}><h3 className="font-semibold">Ближайшие {days} дней</h3><p className="my-2 text-2xl font-bold">{money(w.expected)}</p><p className="text-sm">Счета {money(w.scheduled_invoices)}</p><p className="text-sm">Сделки по вероятности {money(w.weighted_open_deals)}</p><p className="text-xs text-surface-500">{w.deals_count} сделок · до {w.end_date}</p></article>)}</div>{forecast.data.unforecasted_deals>0&&<p className="text-sm">{forecast.data.unforecasted_deals} активных сделок без даты закрытия не вошли в прогноз.</p>}</>}</section>
  <section className="card space-y-4"><h2 className="text-lg font-semibold">Этапы оплаты проекта</h2><p className="text-sm text-surface-500">Сумма счетов соответствует бюджету проекта. Заполненный график виден в задолженности и прогнозе.</p><label>Проект<select className="input ml-2" value={project} onChange={e=>setProject(e.target.value)}><option value="">Выберите проект</option>{projects.data?.map(p=><option key={p.id} value={p.id}>{p.name}{p.budget?` · ${money(p.budget)}`:" · бюджет не задан"}</option>)}</select></label>
  {project&&!plan.data?.length&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);create.mutate({project,installments:titles.map((title,i)=>({title,percentage:f.get(`percent_${i}`),due_date:f.get(`date_${i}`)}))})}}><div className="grid gap-3 sm:grid-cols-4">{titles.map((t,i)=><fieldset className="rounded-xl border border-surface-200 p-3" key={i}><legend>{t}</legend><label>%<input className="input w-full" type="number" min=".01" max="100" step=".01" defaultValue={[30,30,30,10][i]} name={`percent_${i}`} required/></label><label>Срок<input className="input w-full" type="date" min={today(0)} defaultValue={today([0,14,30,45][i])} name={`date_${i}`} required/></label></fieldset>)}</div>{error&&<p role="alert">{error}</p>}<button className="btn-primary" disabled={create.isPending}>Создать 4 этапа</button><p className="text-xs text-surface-500">Из-за округления последняя сумма корректируется на разницу в несколько тыйын, чтобы итог точно совпадал с бюджетом.</p></form>}
  {plan.isError&&<p role="alert">График не загрузился <button onClick={()=>plan.refetch()}>Повторить</button></p>}{plan.data?.map(m=><div className="flex flex-wrap items-center justify-between gap-3 border-t border-surface-200 py-3" key={m.id}><div><strong>{m.position+1}. {m.title}</strong><p>{m.percentage}% · {money(m.amount)} · срок {m.due_date}</p></div><div className="text-right"><p>{m.status==="paid"?"Оплачен":m.status==="overdue"?"Просрочен":m.status==="partial"?"Частично оплачен":"Ожидает"}</p><p className="text-sm text-surface-500">Остаток {money(m.remaining)}</p></div></div>)}</section>
 </div>
}
