# Generated by Django 5.1.15 on 2026-08-08

from django.db import migrations, models


def backfill_phone_e164(apps, schema_editor):
    """Normalize existing phone numbers into phone_e164 so webhook lookups work."""
    from common.phone import normalize_phone

    Client = apps.get_model("clients", "Client")
    for client in Client.objects.exclude(phone="").iterator():
        normalized = normalize_phone(client.phone)
        if normalized:
            Client.objects.filter(pk=client.pk).update(phone_e164=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="phone_e164",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Автоматически нормализуется из phone — используется для поиска клиента из webhook",
                max_length=20,
                verbose_name="Телефон (E.164)",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Сайт"),
                    ("referral", "Рекомендация"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("telegram", "Telegram"),
                    ("call", "Звонок"),
                    ("whatsapp", "WhatsApp"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=50,
                verbose_name="Источник",
            ),
        ),
        migrations.RunPython(backfill_phone_e164, migrations.RunPython.noop),
    ]
