# Generated by Django 5.2.15 on 2026-08-08 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_phone_e164_alter_client_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone_e164',
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(choices=[('website', 'Сайт'), ('referral', 'Рекомендация'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('telegram', 'Telegram'), ('call', 'Звонок'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Источник'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['source'], name='clients_cli_source_a01db6_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='clients_cli_created_4ff9ec_idx'),
        ),
    ]
