# Generated by Django 5.0.14 on 2026-08-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_seed_client_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Telegram chat_id'),
        ),
    ]
