# Generated by Django 5.2.15 on 2026-08-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_action',
            field=models.CharField(blank=True, max_length=255, verbose_name='Следующее действие'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда следующее действие'),
        ),
    ]
