# Generated by Django 5.1.15 on 2026-10-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadstage_default_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='brief_completed',
            field=models.BooleanField(default=False, verbose_name='Анкета заполнена'),
        ),
        migrations.AddField(
            model_name='lead',
            name='business_need',
            field=models.TextField(blank=True, verbose_name='Задача клиента'),
        ),
        migrations.AddField(
            model_name='lead',
            name='decision_maker',
            field=models.CharField(blank=True, max_length=255, verbose_name='ЛПР'),
        ),
        migrations.AddField(
            model_name='lead',
            name='target_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемый срок'),
        ),
    ]
