# Generated by Django 5.1.15 on 2026-10-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partnerpayout_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='public_request_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
