# Generated by Django 5.1.15 on 2026-09-19 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_deal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="allowed_roles",
            field=models.JSONField(blank=True, default=list, verbose_name="Доступные роли"),
        ),
        migrations.AddField(
            model_name="document",
            name="approval_assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_to_approve",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный за согласование",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="approval_deadline",
            field=models.DateField(blank=True, null=True, verbose_name="Срок согласования"),
        ),
        migrations.AddField(
            model_name="document",
            name="external_url",
            field=models.URLField(blank=True, verbose_name="Внешняя ссылка"),
        ),
        migrations.AddField(
            model_name="document",
            name="is_protected",
            field=models.BooleanField(default=False, verbose_name="Защищён от удаления"),
        ),
        migrations.AddField(
            model_name="document",
            name="is_visible_to_client",
            field=models.BooleanField(default=False, verbose_name="Доступен клиенту"),
        ),
        migrations.AddField(
            model_name="document",
            name="source",
            field=models.CharField(
                choices=[("file", "Файл"), ("google_docs", "Google Docs")],
                default="file",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/%Y/%m/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("review", "На согласовании"),
                    ("changes_requested", "Нужны правки"),
                    ("approved", "Согласован"),
                    ("signed", "Подписан"),
                    ("archived", "Архив"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="DocumentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("file", models.FileField(upload_to="documents/versions/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("comment", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "version"), name="unique_document_version"
                    )
                ],
            },
        ),
    ]
