# Generated by Django 5.2.15 on 2026-08-08 12:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("clients", "0005_seed_client_statuses"),
        ("leads", "0003_lead_leads_lead_created_302c6d_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=50, unique=True, verbose_name="Номер"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("open", "В работе"),
                            ("won", "Выиграна"),
                            ("lost", "Проиграна"),
                            ("cancelled", "Отменена"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Подытог"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Скидка (₽)",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Налог (₽)",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Итого"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Себестоимость"
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Прибыль"
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="Маржа (%)"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Оплачено"
                    ),
                ),
                ("won_at", models.DateTimeField(blank=True, null=True, verbose_name="Выиграна")),
                ("lost_at", models.DateTimeField(blank=True, null=True, verbose_name="Проиграна")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлена")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_deals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_deals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal",
                        to="leads.lead",
                        verbose_name="Лид",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сделка",
                "verbose_name_plural": "Сделки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена за единицу"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Скидка (₽)",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Налог (₽)",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Себестоимость (снимок)",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="deals.deal",
                        verbose_name="Сделка",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deal_items",
                        to="catalog.catalogitem",
                        verbose_name="Позиция каталога",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция сделки",
                "verbose_name_plural": "Позиции сделок",
            },
        ),
        migrations.CreateModel(
            name="DealPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Банковский перевод"),
                            ("cash", "Наличные"),
                            ("card", "Карта"),
                            ("crypto", "Криптовалюта"),
                        ],
                        max_length=20,
                        verbose_name="Способ",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, verbose_name="ID транзакции"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                ("paid_at", models.DateTimeField(auto_now_add=True, verbose_name="Оплачен")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Принял",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="deals.deal",
                        verbose_name="Сделка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж сделки",
                "verbose_name_plural": "Платежи сделок",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["status"], name="deals_deal_status_06cb7b_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["client", "status"], name="deals_deal_client__c90fb7_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["created_at"], name="deals_deal_created_9d9de4_idx"),
        ),
    ]
