# Generated by Django 5.1.15 on 2026-10-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('projects', '0005_project_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='projects.project'),
        ),
    ]
