# Generated by Django 5.1.15 on 2026-10-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='expected_close_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
