# Generated by Django 5.0.14 on 2026-08-11 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0006_client_telegram_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PBXConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('provider', models.CharField(choices=[('asterisk', 'Asterisk / FreePBX'), ('mikopbx', 'MikoPBX'), ('yeastar', 'Yeastar'), ('grandstream', 'Grandstream'), ('other', 'Другая')], default='other', max_length=32, verbose_name='Провайдер')),
                ('api_url', models.URLField(blank=True, default='', max_length=512, verbose_name='URL API АТС')),
                ('api_key_encrypted', models.TextField(blank=True, default='', verbose_name='API ключ (зашифрован)')),
                ('ami_host', models.CharField(blank=True, default='', max_length=255, verbose_name='AMI хост')),
                ('ami_port', models.PositiveIntegerField(default=5038, verbose_name='AMI порт')),
                ('ami_user', models.CharField(blank=True, default='', max_length=64, verbose_name='AMI пользователь')),
                ('ami_password_encrypted', models.TextField(blank=True, default='', verbose_name='AMI пароль (зашифрован)')),
                ('ws_url', models.URLField(blank=True, default='', max_length=512, verbose_name='WebSocket URL (WSS)')),
                ('sip_domain', models.CharField(blank=True, default='', max_length=255, verbose_name='SIP домен')),
                ('status', models.CharField(choices=[('connected', 'Подключен'), ('disabled', 'Отключен'), ('error', 'Ошибка')], default='disabled', max_length=32, verbose_name='Статус')),
                ('is_default', models.BooleanField(default=False, verbose_name='Использовать по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Подключение АТС',
                'verbose_name_plural': 'Подключения АТС',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SipAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=32, verbose_name='Внутренний номер')),
                ('password_encrypted', models.TextField(blank=True, default='', verbose_name='Пароль (зашифрован)')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_accounts', to='calls.pbxconnection', verbose_name='Подключение АТС')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'SIP аккаунт',
                'verbose_name_plural': 'SIP аккаунты',
                'ordering': ['extension'],
            },
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_call_id', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='ID звонка (АТС)')),
                ('direction', models.CharField(choices=[('incoming', 'Входящий'), ('outgoing', 'Исходящий')], default='incoming', max_length=16, verbose_name='Направление')),
                ('status', models.CharField(choices=[('answered', 'Отвечен'), ('missed', 'Пропущен'), ('busy', 'Занято'), ('failed', 'Не удался'), ('canceled', 'Отменен'), ('voicemail', 'Голосовая почта')], default='answered', max_length=16, verbose_name='Статус')),
                ('call_type', models.CharField(choices=[('internal', 'Внутренний'), ('external', 'Внешний')], default='external', max_length=16, verbose_name='Тип')),
                ('phone_number', models.CharField(blank=True, default='', max_length=32, verbose_name='Номер')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='clients.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='calls.pbxconnection', verbose_name='Подключение АТС')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['direction', 'status'], name='calls_callr_directi_35a7f3_idx'), models.Index(fields=['-started_at'], name='calls_callr_started_ab8d33_idx'), models.Index(fields=['phone_number'], name='calls_callr_phone_n_2fb069_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='callrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('external_call_id__gt', '')), fields=('connection', 'external_call_id'), name='uniq_connection_external_call'),
        ),
    ]
