# Generated by Django 5.0.14 on 2026-08-08 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Чек-лист адаптации',
                'verbose_name_plural': 'Чек-листы адаптации',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mentorship.checklist', verbose_name='Чек-лист')),
            ],
            options={
                'verbose_name': 'Пункт чек-листа',
                'verbose_name_plural': 'Пункты чек-листа',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('paused', 'Приостановлен')], default='active', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateField(verbose_name='Дата начала')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_pairs', to=settings.AUTH_USER_MODEL, verbose_name='Новичок')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_pairs', to=settings.AUTH_USER_MODEL, verbose_name='Наставник')),
            ],
            options={
                'verbose_name': 'Пара наставник-новичок',
                'verbose_name_plural': 'Пары наставник-новичок',
                'ordering': ['-created_at'],
                'unique_together': {('mentor', 'mentee')},
            },
        ),
        migrations.CreateModel(
            name='MenteeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Выполнено'), ('overdue', 'Просрочено')], default='pending', max_length=20, verbose_name='Статус')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mentorship.mentorshippair', verbose_name='Пара')),
            ],
            options={
                'verbose_name': 'Задача новичка',
                'verbose_name_plural': 'Задачи новичка',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenteeEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 — Требуется много работы'), (2, '2 — Ниже ожиданий'), (3, '3 — Удовлетворительно'), (4, '4 — Хорошо'), (5, '5 — Отлично')], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оценщик')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='mentorship.mentorshippair', verbose_name='Пара')),
            ],
            options={
                'verbose_name': 'Оценка новичка',
                'verbose_name_plural': 'Оценки новичков',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenteeChecklistProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.checklist', verbose_name='Чек-лист')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_progress', to='mentorship.mentorshippair', verbose_name='Пара')),
            ],
            options={
                'verbose_name': 'Прогресс чек-листа',
                'verbose_name_plural': 'Прогресс чек-листов',
                'unique_together': {('pair', 'checklist')},
            },
        ),
        migrations.CreateModel(
            name='MenteeChecklistItemProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.checklistitem', verbose_name='Пункт')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mentorship.menteechecklistprogress', verbose_name='Прогресс')),
            ],
            options={
                'verbose_name': 'Прогресс пункта',
                'verbose_name_plural': 'Прогресс пунктов',
                'unique_together': {('progress', 'item')},
            },
        ),
    ]
